name: connectinno_case_client
description: "Note App."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  go_router: ^14.6.2
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4
  hive_ce_generator: ^1.9.3


flutter:
  uses-material-design: true
