// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:connectinno_case_client/data/models/note/note_model.dart';
import 'package:connectinno_case_client/data/models/queue/queue_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NoteModelAdapter());
    registerAdapter(QueueModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NoteModelAdapter());
    registerAdapter(QueueModelAdapter());
  }
}
